pub const MARGIN: f32 = 25.0;
pub const WINDOW_HEIGHT: f32 = BOARD_SIZE + MARGIN * 3. + TITLE_SIZE + SUBTITLE_SIZE;
pub const WINDOW_WIDTH: f32 = 400.0;

pub const TITLE_POSITION: (f32, f32) = (MARGIN, MARGIN);
pub const TITLE_SIZE: f32 = 50.0;

pub const SUBTITLE_POSITION: (f32, f32) = (MARGIN, MARGIN + TITLE_SIZE);
pub const SUBTITLE_SIZE: f32 = 13.0;

pub const SCOREBOARD_WIDTH: f32 = 95.0;
pub const SCOREBOARD_HEIGHT: f32 = 50.0;
pub const SCOREBOARD_POSITION: (f32, f32) = (WINDOW_WIDTH - SCOREBOARD_WIDTH - MARGIN, MARGIN);

pub const SCORE_MARGIN: f32 = 5.0;
pub const SCORE_BOUNDING: (f32, f32) = (
    SCOREBOARD_WIDTH - 2. * SCORE_MARGIN,
    (SCOREBOARD_HEIGHT - SCORE_MARGIN * 3.) / 2.,
);

pub const SCORE_TITLE_POSITION: (f32, f32) = (
    SCOREBOARD_POSITION.0 + SCORE_MARGIN,
    SCOREBOARD_POSITION.1 + SCORE_MARGIN,
);
pub const SCORE_TITLE_SIZE: f32 = 15.0;

pub const SCORE_POSITION: (f32, f32) = (
    SCORE_TITLE_POSITION.0,
    SCORE_BOUNDING.1 + SCORE_TITLE_POSITION.1,
);
pub const SCORE_SIZE: f32 = 25.0;

pub const BOARD_POSITION: (f32, f32) = (MARGIN, SUBTITLE_POSITION.1 + MARGIN);
pub const BOARD_SIZE: f32 = WINDOW_WIDTH - 2. * MARGIN;
pub const TILE_MARGIN: f32 = 10.0;
pub const TILE_SIZE: f32 = (BOARD_SIZE - 5. * TILE_MARGIN) / 4.;

pub const WIN_BUTTON_TEXT: f32 = TITLE_SIZE / 2.;
pub const WIN_BUTTON_SIZE: (f32, f32) = (WINDOW_WIDTH / 3., WIN_BUTTON_TEXT + MARGIN);
pub const WIN_BUTTON_POSITION: (f32, f32) = (WINDOW_WIDTH / 3., WINDOW_HEIGHT / 3. + 3. * MARGIN);
